### ISSUE TITLE
When suggesting code Codeium duplicates existing lines on the code bellow.

### ISSUE THREAD

**Issue by rrebelo62** [Exafunction/CodeiumVisualStudio#101]
![CodeiumProblem](https://github.com/user-attachments/assets/2aaeaf40-cd5a-447d-a11f-1572df75aa26)

See picture above. When Codeium makes a suggestion, existing lines in code are duplicated.

**Comment by jdussail** [comment]
Same happens to me, and a huge chunk, so much that what I'm typing gets out of view.

**Comment by Zallist** [comment]
I've fixed this in https://github.com/Exafunction/CodeiumVisualStudio/pull/133 I believe. It seems (at least for me) to be related to mixed \r\n and \n line endings.

**Comment by rrebelo62** [comment]
I tested your MR and it does fix this issue.

Thank you, @Zallist.

**Comment by versile2** [comment]
I'm using V 1.8.88 currently in Visual Studio and still getting this behavior which makes auto suggest unusable. It's suggesting pages of code to the point I can't even see what I'm typing without hitting the Escape key repeatedly.

**Comment by versile2** [comment]
> I just released 1.8.89 with this fix included in it. Could you please update and let me know if this persists?

It appears to be, I'll use it more tomorrow and report my results if anything negative.
